### ISSUE TITLE
Python 2 and 3 compatibility priorities

### ISSUE THREAD

**Issue by IronSean** [arachnidlabs/cyflash#11]
What are the priorities with Python 2 and 3 compatibility? As it currently stands the code is not fully compatible with with both versions. Since this is a utility that installs and runs independently, I'm not sure Python 2 support needs to be a priority. Most systems have both installed, and some just python3, so it can be insatalled via `python3 setup.py install` easily enough.

If compatibility is important, I'll recommend adding the `future` module as a requirement. If Python2 support isn't important, I'll clean up things for a pure Python3 package.

**Comment by jsiverskog** [comment]
As far as I know, this is done.
