### ISSUE TITLE
Bug in Bootloader component fixed?

### ISSUE THREAD

**Issue by C47D** [arachnidlabs/cyflash#18]
Did Cypress fixed the issue of the #define Bootloader_RSP_SIZE_GET_METADATA (0x56u) in Bootloader_PVT.h should be #define Bootloader_RSP_SIZE_GET_METADATA (56u) on the current Creator 4.1?
If not, the new "way" they upload components without requiring to wait for the next Creator release might resolve this problem, or at least make it easier to resolve.

**Comment by jsiverskog** [comment]
I can confirm that it's fixed in bootloader component version 1.60.

**Comment by C47D** [comment]
Thanks @jsiverskog, i just updated the component today.
On the component changes they also point out:

> Implemented enhancement to the metadata update routine to avoid an unnecessary flash write operation

This improvement can be also applicable to cyflash?

**Comment by jsiverskog** [comment]
As far as I know the metadata isn't explicitly updated from cyflash, it's probably an internal improvement in the bootloader.

**Comment by C47D** [comment]
Thanks for the help, i will close this issue as the initial problem is now fixed.
