### ISSUE TITLE
GUI front end?

### ISSUE THREAD

**Issue by C47D** [arachnidlabs/cyflash#24]
Not really a issue,

* Do you have any plans to do a tiny GUI front end for this tool?
* Do you think it can be useful?

Regards.
Carlos

**Comment by jsiverskog** [comment]
Hello Carlos,
This project is used by developers writing code for various PSoC devices - they should be comfortable with using the command line. Creating a GUI doesn't make sense for me - it brings in a lot of complications with unclear benefits.

Users not comfortable with using the command line is most likely using Windows and can thus just use Cypress' own GUI tools.

**Comment by C47D** [comment]
Thanks for the reply @jsiverskog, indeed the GUI would bring extra work.
